#!/bin/sh
set -e
first=\$1
cmd=\$*
containerCookieList="\$COOKIES_LIST.\$CNAME"
echo \${cmd/\$1/}
if [ \$1 == "ca" ]; then
    while read line;
    do
        containerCookieList="\$COOKIES_LIST.\$line"
        for job in \$(cat \$containerCookieList | grep -v "#" | paste -s -d ' '); do
            { export JD_COOKIE=\$job && node \${cmd/\$1/}
            }&
        done
    done</scripts/logs/dockers.list
elif [ \$1 == "conc" ]; then
    containerCookieList="\$COOKIES_LIST.\$CNAME"
    for job in \$(cat \$containerCookieList | grep -v "#" | paste -s -d ' '); do
        { export JD_COOKIE=\$job && node \${cmd/\$1/}
        }&
    done
elif [ -n "\$(echo \$first | sed -n "/^[0-9]\+\$/p")" ]; then
    echo "\$(echo \$first | sed -n "/^[0-9]\+\$/p")"
    { export JD_COOKIE=\$(sed -n "\${first}p" \$containerCookieList) && node \${cmd/\$1/}
    }&
elif [ -n "\$(cat \$containerCookieList  | grep "pt_pin=\$first")" ];then
    echo "\$(cat \$containerCookieList  | grep "pt_pin=\$first")"
    { export JD_COOKIE=\$(cat \$containerCookieList | grep "pt_pin=\$first") && node \${cmd/\$1/}
    }&
else
    { export JD_COOKIE=\$(cat \$containerCookieList | grep -v "#" | paste -s -d '&') && node \$*
    }&
fi